apiVersion: v1
kind: Namespace
metadata:
  name: cattle-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: rocketchat
---
apiVersion: v1
kind: Namespace
metadata:
  name: registry
---
apiVersion: v1 # will add jira-servicemanagement app
kind: Namespace
metadata:
  name: anchore
