apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: rocketchat
---
apiVersion: v1
kind: Namespace
metadata:
  name: registry
---
apiVersion: v1 
kind: Namespace
metadata:
  name: anchore
